# Generated by Django 5.1.6 on 2025-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=80)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'Active'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10)),
            ],
        ),
    ]
