# Generated by Django 5.1.6 on 2025-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
