# Generated by Django 5.1.7 on 2025-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_carbooking_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
