# Generated by Django 5.1.7 on 2025-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_carbooking_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
