# Generated by Django 5.1.7 on 2025-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_carbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
