# Generated by Django 5.1.7 on 2025-06-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_carbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
