# Generated by Django 5.0.2 on 2025-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_carbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='email',
            field=models.TextField(max_length=500),
        ),
    ]
