# Generated by Django 5.1.7 on 2025-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_carbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
