# Generated by Django 5.0.2 on 2025-06-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_carbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='admin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='client_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
