# Generated by Django 5.1.7 on 2025-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_carbooking_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='admin_confirmed',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='client_confirmed',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='confirmation_code',
        ),
    ]
