# Generated by Django 5.0.2 on 2025-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_carbooking_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
